version: '3'

services:
  app:
    container_name: nominuke-app
    build: ./docker/php
    volumes:
      - ./src:/var/www
      - bootstrap:/var/www/laravel/bootstrap
      - vendor:/var/www/laravel/vendor
      - node_modules:/var/www/laravel/node_modules
      - storage:/var/www/laravel/storage
    environment:
      TZ: Asia/Tokyo

  web:
    container_name: nominuke-web
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    ports:
      - 8000:80
    volumes:
      - ./src:/var/www
    depends_on:
      - app

  db:
    build: ./docker/mysql
    container_name: nominuke-db
    volumes:
      - mysql:/var/lib/mysql

volumes:
  bootstrap:
  vendor:
  node_modules:
  storage:
  mysql:
