version: 2.1
general:
  branches:
    only:
      - main
      - develop

jobs:
  build:
    docker:
      - image: cimg/php:8.1.11-node
      - image: cimg/mysql:8.0
        environment:
          MYSQL_DATABASE: circleci_testing
          MYSQL_USER: laravel
          MYSQL_ROOT_PASSWORD: secret

    steps:
      - checkout
      - run: sudo composer self-update --1
      - restore_cache:
          key: composer-v1-{{ checksum "./src/project/composer.lock" }}
      - run: |
          cd src/project
          composer install -n --prefer-dist
      - save_cache:
          key: composer-v1-{{ checksum "./src/project/composer.lock" }}
          paths:
            - ./src/project/vendor
      - restore_cache:
          key: npm-v1-{{ checksum "./src/project/package-lock.json" }}
      - run:
          name: npm ci
          command: |
            cd src/project
            if [ ! -d ./src/project/node_modules ]; then
              npm ci
            fi
      - save_cache:
          key: npm-v1-{{ checksum "./src/project/package-lock.json" }}
          paths:
            - ./src/project/node_modules
      - run: |
          cd src/project
          npm run dev
      - run: |
          cd src/project
          vendor/bin/phpunit
