version: 2.1
general:
  branches:
    only:
      - main
      - develop

jobs:
  build:
    docker:
      - image: cimg/php:8.1.11-node
      - image: cimg/mysql:8.0
        command: mysqld --default-authentication-plugin=mysql_native_password
    environment:
      - DB_CONNECTION: circleci_testing

    steps:
      - checkout
      - run: sudo composer self-update --1
      - run: ls src
      - run: pwd
      - restore_cache:
          key: composer-v1-{{ checksum "./src/project/composer.lock" }}
      - run: composer install -n --prefer-dist
      - save_cache:
          key: composer-v1-{{ checksum "./src/project/composer.lock" }}
          paths:
            - ./src/project/vendor
      - restore_cache:
          key: npm-v1-{{ checksum "./src/project/package-lock.json" }}
      - run:
          name: npm ci
          command: |
            if [ ! -d ./src/project/node_modules ]; then
              npm ci
            fi
      - save_cache:
          key: npm-v1-{{ checksum "./src/project/package-lock.json" }}
          paths:
            - ./src/project/node_modules
      - run: npm run dev
      - run: ./src/project/vendor/bin/phpunit
